/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 120002
 Source Host           : localhost:5432
 Source Catalog        : test4bt
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 120002
 File Encoding         : 65001

 Date: 18/08/2020 21:43:32
*/


-- ----------------------------
-- Sequence structure for order_products_op_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."order_products_op_id_seq";
CREATE SEQUENCE "public"."order_products_op_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for orders_order_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."orders_order_id_seq";
CREATE SEQUENCE "public"."orders_order_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for products_product_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."products_product_id_seq";
CREATE SEQUENCE "public"."products_product_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for order_products
-- ----------------------------
DROP TABLE IF EXISTS "public"."order_products";
CREATE TABLE "public"."order_products" (
  "order_id" int8 NOT NULL,
  "product_id" int8 NOT NULL,
  "op_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
)
)
;
COMMENT ON COLUMN "public"."order_products"."order_id" IS 'ID заказа';
COMMENT ON COLUMN "public"."order_products"."product_id" IS 'ID товара';

-- ----------------------------
-- Records of order_products
-- ----------------------------
INSERT INTO "public"."order_products" VALUES (2, 1, 1);
INSERT INTO "public"."order_products" VALUES (2, 7, 2);
INSERT INTO "public"."order_products" VALUES (3, 7, 3);
INSERT INTO "public"."order_products" VALUES (5, 6, 4);
INSERT INTO "public"."order_products" VALUES (5, 1, 5);
INSERT INTO "public"."order_products" VALUES (6, 2, 6);
INSERT INTO "public"."order_products" VALUES (6, 3, 7);
INSERT INTO "public"."order_products" VALUES (7, 1, 8);
INSERT INTO "public"."order_products" VALUES (1, 1, 9);
INSERT INTO "public"."order_products" VALUES (1, 2, 10);
INSERT INTO "public"."order_products" VALUES (10, 1, 11);
INSERT INTO "public"."order_products" VALUES (11, 1, 12);
INSERT INTO "public"."order_products" VALUES (11, 2, 14);
INSERT INTO "public"."order_products" VALUES (11, 3, 15);
INSERT INTO "public"."order_products" VALUES (12, 1, 16);
INSERT INTO "public"."order_products" VALUES (13, 2, 22);
INSERT INTO "public"."order_products" VALUES (14, 1, 23);
INSERT INTO "public"."order_products" VALUES (15, 1, 26);
INSERT INTO "public"."order_products" VALUES (15, 2, 28);
INSERT INTO "public"."order_products" VALUES (2, 2, 29);
INSERT INTO "public"."order_products" VALUES (17, 2, 30);
INSERT INTO "public"."order_products" VALUES (18, 2, 31);
INSERT INTO "public"."order_products" VALUES (19, 2, 32);
INSERT INTO "public"."order_products" VALUES (20, 2, 33);
INSERT INTO "public"."order_products" VALUES (21, 2, 34);
INSERT INTO "public"."order_products" VALUES (21, 3, 35);
INSERT INTO "public"."order_products" VALUES (22, 2, 36);
INSERT INTO "public"."order_products" VALUES (26, 2, 37);
INSERT INTO "public"."order_products" VALUES (27, 2, 38);
INSERT INTO "public"."order_products" VALUES (27, 3, 39);
INSERT INTO "public"."order_products" VALUES (30, 5, 40);
INSERT INTO "public"."order_products" VALUES (31, 2, 41);
INSERT INTO "public"."order_products" VALUES (32, 2, 42);
INSERT INTO "public"."order_products" VALUES (33, 5, 43);
INSERT INTO "public"."order_products" VALUES (33, 3, 44);
INSERT INTO "public"."order_products" VALUES (33, 2, 45);
INSERT INTO "public"."order_products" VALUES (34, 5, 46);
INSERT INTO "public"."order_products" VALUES (34, 2, 48);
INSERT INTO "public"."order_products" VALUES (35, 5, 49);
INSERT INTO "public"."order_products" VALUES (35, 2, 50);
INSERT INTO "public"."order_products" VALUES (36, 2, 51);
INSERT INTO "public"."order_products" VALUES (37, 5, 52);
INSERT INTO "public"."order_products" VALUES (37, 3, 53);
INSERT INTO "public"."order_products" VALUES (37, 2, 54);
INSERT INTO "public"."order_products" VALUES (38, 5, 55);
INSERT INTO "public"."order_products" VALUES (39, 2, 56);
INSERT INTO "public"."order_products" VALUES (40, 5, 57);
INSERT INTO "public"."order_products" VALUES (40, 3, 58);
INSERT INTO "public"."order_products" VALUES (41, 2, 59);
INSERT INTO "public"."order_products" VALUES (42, 2, 60);
INSERT INTO "public"."order_products" VALUES (4, 3, 61);
INSERT INTO "public"."order_products" VALUES (43, 3, 62);
INSERT INTO "public"."order_products" VALUES (44, 3, 63);
INSERT INTO "public"."order_products" VALUES (45, 3, 64);
INSERT INTO "public"."order_products" VALUES (46, 3, 65);
INSERT INTO "public"."order_products" VALUES (47, 3, 66);
INSERT INTO "public"."order_products" VALUES (48, 3, 67);
INSERT INTO "public"."order_products" VALUES (49, 4, 70);
INSERT INTO "public"."order_products" VALUES (49, 3, 71);
INSERT INTO "public"."order_products" VALUES (49, 5, 73);

-- ----------------------------
-- Table structure for orders
-- ----------------------------
DROP TABLE IF EXISTS "public"."orders";
CREATE TABLE "public"."orders" (
  "dt_add" date NOT NULL DEFAULT CURRENT_DATE,
  "price" numeric(10,2) NOT NULL DEFAULT 0,
  "status" int2 NOT NULL DEFAULT 1,
  "order_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
)
)
;
COMMENT ON COLUMN "public"."orders"."dt_add" IS 'Дата создания заказа';
COMMENT ON COLUMN "public"."orders"."price" IS 'Сумма товаров заказа';
COMMENT ON COLUMN "public"."orders"."status" IS 'Статус заказа:
1 - Заказ создан
2 - Заказ оплачен';

-- ----------------------------
-- Records of orders
-- ----------------------------
INSERT INTO "public"."orders" VALUES ('2020-08-16', 3.00, 2, 1);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 12.00, 1, 12);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 2, 13);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 12.00, 3, 14);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 16.00, 1, 15);
INSERT INTO "public"."orders" VALUES ('2020-08-16', 4.00, 1, 2);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 3, 17);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 1, 18);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 3, 19);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 3, 20);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 2, 22);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 2, 26);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 127.00, 3, 27);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 11.50, 3, 30);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 2, 31);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 2, 32);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 138.50, 3, 33);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 15.50, 2, 34);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 15.50, 3, 35);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 3, 36);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 138.50, 3, 37);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 11.50, 3, 38);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 2, 39);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 134.50, 3, 40);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 3, 41);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 4.00, 3, 42);
INSERT INTO "public"."orders" VALUES ('2020-08-05', 123.00, 3, 4);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 123.00, 3, 43);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 123.00, 2, 44);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 123.00, 2, 45);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 123.00, 2, 46);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 123.00, 3, 47);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 123.00, 3, 48);
INSERT INTO "public"."orders" VALUES ('2020-08-18', 146.50, 1, 49);

-- ----------------------------
-- Table structure for products
-- ----------------------------
DROP TABLE IF EXISTS "public"."products";
CREATE TABLE "public"."products" (
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'Unknown'::character varying,
  "price" numeric(10,2) NOT NULL DEFAULT 0,
  "count" int4 NOT NULL DEFAULT 0,
  "product_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
)
)
;
COMMENT ON COLUMN "public"."products"."name" IS 'Название товара';
COMMENT ON COLUMN "public"."products"."price" IS 'Цена товара';
COMMENT ON COLUMN "public"."products"."count" IS 'Кол-во товаров';

-- ----------------------------
-- Records of products
-- ----------------------------
INSERT INTO "public"."products" VALUES ('Карандаш', 12.00, 100, 4);
INSERT INTO "public"."products" VALUES ('Ручка', 11.50, 100, 5);
INSERT INTO "public"."products" VALUES ('Кокосик :о', 123.00, 100, 3);
INSERT INTO "public"."products" VALUES ('Пенал', 4.00, 100, 2);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."order_products_op_id_seq"
OWNED BY "public"."order_products"."op_id";
SELECT setval('"public"."order_products_op_id_seq"', 74, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."orders_order_id_seq"
OWNED BY "public"."orders"."order_id";
SELECT setval('"public"."orders_order_id_seq"', 50, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."products_product_id_seq"
OWNED BY "public"."products"."product_id";
SELECT setval('"public"."products_product_id_seq"', 6, true);

-- ----------------------------
-- Uniques structure for table order_products
-- ----------------------------
ALTER TABLE "public"."order_products" ADD CONSTRAINT "order_products_order_id_product_id_key" UNIQUE ("order_id", "product_id");

-- ----------------------------
-- Primary Key structure for table order_products
-- ----------------------------
ALTER TABLE "public"."order_products" ADD CONSTRAINT "order_products_pkey" PRIMARY KEY ("op_id");

-- ----------------------------
-- Checks structure for table orders
-- ----------------------------
ALTER TABLE "public"."orders" ADD CONSTRAINT "checkStatus" CHECK (status = ANY (ARRAY[1, 2, 3]));
ALTER TABLE "public"."orders" ADD CONSTRAINT "сheckPrice" CHECK (price >= 0::numeric);

-- ----------------------------
-- Primary Key structure for table orders
-- ----------------------------
ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("order_id");

-- ----------------------------
-- Checks structure for table products
-- ----------------------------
ALTER TABLE "public"."products" ADD CONSTRAINT "checkСount" CHECK (count::numeric >= 0::numeric);
ALTER TABLE "public"."products" ADD CONSTRAINT "checkPrice" CHECK (price >= 0::numeric);

-- ----------------------------
-- Primary Key structure for table products
-- ----------------------------
ALTER TABLE "public"."products" ADD CONSTRAINT "products_pkey" PRIMARY KEY ("product_id");
